// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Osmo.ConneX.Providers;

#nullable disable

namespace Osmo.ConneX.Migrations.ConneXMetrics
{
    [DbContext(typeof(ConneXMetricsProviderContext))]
    [Migration("20250311201358_AddHandlerStatistics")]
    partial class AddHandlerStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Osmo.Common.Messages.MqttMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<string>("PayloadAsString")
                        .HasColumnType("text")
                        .HasColumnName("payload_as_string");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.ToTable("mqtt_messages");
                });

            modelBuilder.Entity("Osmo.ConneX.Models.ConneXMetaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("connex_metadata");
                });

            modelBuilder.Entity("Osmo.ConneX.Models.HandlerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HandlerIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("handler_identifier");

                    b.Property<string>("HandlerName")
                        .HasColumnType("text")
                        .HasColumnName("handler_name");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("rawdata");

                    b.Property<Guid>("RelatedMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_message_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("connex_handler_events");
                });

            modelBuilder.Entity("Osmo.ConneX.Models.HandlerStatistics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("DevicesFailedOn3DSystem")
                        .HasColumnType("integer")
                        .HasColumnName("devices_failed_on_3d_system");

                    b.Property<int>("DevicesFailedOnLaser")
                        .HasColumnType("integer")
                        .HasColumnName("devices_failed_on_laser");

                    b.Property<int>("DevicesFailedOnProgrammer")
                        .HasColumnType("integer")
                        .HasColumnName("devices_failed_on_programmer");

                    b.Property<int>("DevicesFailedREST")
                        .HasColumnType("integer")
                        .HasColumnName("devices_failed_rest");

                    b.Property<int>("DevicesFailedVision")
                        .HasColumnType("integer")
                        .HasColumnName("devices_failed_vision");

                    b.Property<int>("DevicesPickedInput")
                        .HasColumnType("integer")
                        .HasColumnName("devices_picked_input");

                    b.Property<double>("HandlerYield")
                        .HasColumnType("double precision")
                        .HasColumnName("handler_yield");

                    b.Property<int>("JobAssistanceTime")
                        .HasColumnType("integer")
                        .HasColumnName("job_assistance_time");

                    b.Property<DateTime>("JobCompletionEstimate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("job_completion_estimate");

                    b.Property<int>("JobProcessingTime")
                        .HasColumnType("integer")
                        .HasColumnName("job_processing_time");

                    b.Property<double>("ProgrammerYield")
                        .HasColumnType("double precision")
                        .HasColumnName("programmer_yield");

                    b.Property<string>("RelatedHandlerId")
                        .HasColumnType("text")
                        .HasColumnName("related_handler_id");

                    b.Property<Guid>("RelatedMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_message_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<double>("SystemYield")
                        .HasColumnType("double precision")
                        .HasColumnName("system_yield");

                    b.Property<int>("TotalFail")
                        .HasColumnType("integer")
                        .HasColumnName("total_fail");

                    b.Property<int>("TotalPass")
                        .HasColumnType("integer")
                        .HasColumnName("total_pass");

                    b.Property<int>("Uph")
                        .HasColumnType("integer")
                        .HasColumnName("uph");

                    b.HasKey("Id", "TimeStamp");

                    b.ToTable("handler_statistics");
                });

            modelBuilder.Entity("Osmo.ConneX.Models.ProgrammingStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("BlankCheckDuration")
                        .HasColumnType("integer")
                        .HasColumnName("blank_check_duration");

                    b.Property<long>("BytesProgrammed")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_programmed");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<string>("CodeName")
                        .HasColumnType("text")
                        .HasColumnName("code_name");

                    b.Property<int>("EraseDuration")
                        .HasColumnType("integer")
                        .HasColumnName("erase_duration");

                    b.Property<int>("Overall")
                        .HasColumnType("integer")
                        .HasColumnName("overall");

                    b.Property<int>("Overhead")
                        .HasColumnType("integer")
                        .HasColumnName("overhead");

                    b.Property<int>("ProgramDuration")
                        .HasColumnType("integer")
                        .HasColumnName("program_duration");

                    b.Property<Guid>("RelatedDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_device_id");

                    b.Property<Guid>("RelatedJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_job_id");

                    b.Property<Guid>("RelatedProgrammerId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_programmer_id");

                    b.Property<int>("VerifyDuration")
                        .HasColumnType("integer")
                        .HasColumnName("verify_duration");

                    b.HasKey("Id", "TimeStamp");

                    b.ToTable("programming_statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
